export const LOAD_POKEMON_LIST = 'LOAD_POKEMON_LIST';
export const LOAD_POKEMON_CARD = 'LOAD_POKEMON_CARD';
export const LOAD_CARD_DETAILS = 'LOAD_CARD_DETAILS';
export const LOAD_SPECIES_DETAILS = 'LOAD_SPECIES_DETAILS';
export const FETCH_DETAILS = 'FETCH_DETAILS';
export const GET_POKE_TO_DISP_ID = 'GET_POKE_TO_DISP_ID';